# Append selected empirical outputs to coding samples.

coding_output_registry <- function(manifest) {
  entries <- manifest$coding_outputs %||% list()
  ids <- names(entries)
  if (length(entries) && (is.null(ids) || any(!nzchar(ids)) || anyDuplicated(ids))) {
    stop("coding_outputs must be a named mapping with unique IDs.", call. = FALSE)
  }
  entries
}

resolve_coding_outputs <- function(spec, manifest) {
  ids <- unlist(spec$outputs %||% character(), use.names = FALSE)
  registry <- coding_output_registry(manifest)
  missing <- setdiff(ids, names(registry))
  if (length(missing)) {
    stop("Coding sample references unknown selected outputs: ", paste(missing, collapse = ", "), call. = FALSE)
  }
  unname(registry[ids])
}

format_sample_table_value <- function(x) {
  if (is.numeric(x)) return(formatC(x, format = "f", digits = 3))
  as.character(x)
}

selected_table_lines <- function(item) {
  path <- item$file %||% ""
  if (!file.exists(path)) stop("Selected coding-sample table does not exist: ", path, call. = FALSE)
  table <- utils::read.csv(path, check.names = FALSE, stringsAsFactors = FALSE)

  rows <- unlist(item$rows %||% character(), use.names = FALSE)
  if (length(rows)) {
    row_col <- item$columns[[1L]]
    missing_rows <- setdiff(rows, table[[row_col]])
    if (length(missing_rows)) {
      stop("Selected coding-sample table rows are missing from ", path, ": ", paste(missing_rows, collapse = ", "), call. = FALSE)
    }
    table <- table[match(rows, table[[row_col]]), , drop = FALSE]
  }

  columns <- unlist(item$columns %||% names(table), use.names = FALSE)
  missing_columns <- setdiff(columns, names(table))
  if (length(missing_columns)) {
    stop("Selected coding-sample table columns are missing from ", path, ": ", paste(missing_columns, collapse = ", "), call. = FALSE)
  }
  table <- table[columns]
  table[] <- lapply(table, format_sample_table_value)

  labels <- unlist(item$labels %||% columns, use.names = FALSE)
  if (length(labels) != length(columns)) {
    stop("Selected coding-sample table labels must match the selected columns.", call. = FALSE)
  }
  names(table) <- labels
  as.character(knitr::kable(table, format = "pipe", row.names = FALSE))
}

selected_figure_lines <- function(item) {
  path <- item$file %||% ""
  if (!file.exists(path)) stop("Selected coding-sample figure does not exist: ", path, call. = FALSE)
  sample_path <- paste0("../../", path)
  c(paste0("![](", sample_path, "){width=95%}"))
}

coding_sample_output_lines <- function(spec, manifest) {
  items <- resolve_coding_outputs(spec, manifest)
  if (!length(items)) return(character())
  pieces <- lapply(items, function(item) {
    kind <- item$type %||% ""
    content <- switch(
      kind,
      table = selected_table_lines(item),
      figure = selected_figure_lines(item),
      stop("Unsupported coding-sample output type: ", kind, call. = FALSE)
    )
    c(
      "",
      paste0("## ", item$title %||% basename(item$file)),
      "",
      item$description %||% "",
      "",
      content,
      ""
    )
  })
  c("", "# Selected Outputs", "",
    "The tables and figures below are generated by the analyses from which the preceding excerpts are drawn.",
    unlist(pieces, use.names = FALSE))
}
