# Shared rendering and validation helpers for application-sample PDFs.


# Application samples use the current paper's PDF typography and page geometry.
# The paper gets its standard article class from the project configuration; sample
# QMDs are rendered from a nested work directory, so set that class explicitly.
paper_sample_metadata <- function(source_metadata, variant, manifest) {
  meta <- source_metadata
  meta$thanks <- NULL
  meta$author <- manifest$identity[[variant]]$author
  meta$format <- meta$format %||% list()
  meta$format$pdf <- utils::modifyList(
    meta$format$pdf %||% list(),
    list(documentclass = "article", `pdf-engine` = "xelatex")
  )
  meta
}


paper_title_with_subtitle <- function(source_metadata) {
  parts <- trimws(as.character(c(source_metadata$title %||% "", source_metadata$subtitle %||% "")))
  parts <- parts[nzchar(parts)]
  if (!length(parts)) stop("Current paper metadata must include a title.", call. = FALSE)
  paste(parts, collapse = ": ")
}

quoted_paper_title <- function(source_metadata, terminal_period = FALSE) {
  ending <- if (isTRUE(terminal_period)) ".”" else "”"
  paste0("“", paper_title_with_subtitle(source_metadata), ending)
}

application_sample_make_target <- function() {
  "make samples"
}

application_sample_makefile_url <- function(manifest) {
  repository_url <- sub("/+$", "", manifest$paper$repository_url %||% "")
  if (!nzchar(repository_url)) stop("Application-sample manifest is missing paper.repository_url.", call. = FALSE)
  paste0(repository_url, "/blob/main/Makefile")
}

application_sample_build_script <- function() {
  "scripts/run_full_build.sh"
}

application_sample_build_script_url <- function(manifest) {
  repository_url <- sub("/+$", "", manifest$paper$repository_url %||% "")
  if (!nzchar(repository_url)) stop("Application-sample manifest is missing paper.repository_url.", call. = FALSE)
  paste0(repository_url, "/blob/main/", application_sample_build_script())
}

application_sample_file_url <- function(path, manifest) {
  repository_url <- sub("/+$", "", manifest$paper$repository_url %||% "")
  if (!nzchar(repository_url)) stop("Application-sample manifest is missing paper.repository_url.", call. = FALSE)
  paste0(repository_url, "/blob/main/", path)
}

application_sample_file_reference <- function(path, variant, manifest) {
  code <- paste0("`", path, "`")
  if (!identical(variant, "named")) return(code)
  paste0("[", code, "](", application_sample_file_url(path, manifest), ")")
}

application_sample_site_root <- function(manifest) {
  full_paper_url <- manifest$paper$full_paper_url %||% ""
  if (!nzchar(full_paper_url)) stop("Application-sample manifest is missing paper.full_paper_url.", call. = FALSE)
  sub("[^/]+$", "", full_paper_url)
}

application_sample_document_url <- function(kind, sample_id, variant, manifest) {
  paste0(
    application_sample_site_root(manifest),
    "application-samples/",
    basename(application_sample_output_path(kind, sample_id, variant, manifest))
  )
}

application_sample_availability_sentence <- function(kind, sample_id, variant, manifest, full_paper = TRUE) {
  paper_phrase <- if (isTRUE(full_paper)) "the full paper" else "the paper"
  if (!identical(variant, "named")) {
    return(paste0(
      "This project may have been updated since this file was generated; the most up-to-date versions of this document, ",
      paper_phrase, ", and its replication package are available online for those interested."
    ))
  }

  document <- paste0("[document](", application_sample_document_url(kind, sample_id, variant, manifest), ")")
  paper <- paste0("[paper](", manifest$paper$full_paper_url, ")")
  replication_package <- paste0("[replication package](", manifest$paper$repository_url, ")")
  paper_phrase <- if (isTRUE(full_paper)) paste0("the full ", paper) else paste0("the ", paper)
  paste0(
    "This project may have been updated since this file was generated; the most up-to-date versions of this ",
    document, ", ", paper_phrase, ", and the ", replication_package, " are available online for those interested."
  )
}

application_sample_make_reference <- function(variant, manifest) {
  target <- paste0("`", application_sample_make_target(), "`")
  if (!identical(variant, "named")) return(target)
  paste0("[", target, "](", application_sample_makefile_url(manifest), ")")
}

application_sample_build_sentence <- function(variant, manifest) {
  script <- application_sample_build_script()
  script_reference <- if (identical(variant, "named")) {
    paste0("[`", script, "`](", application_sample_build_script_url(manifest), ")")
  } else {
    paste0("`", script, "`")
  }
  paste0(
    "This PDF can be generated by running ", application_sample_make_reference(variant, manifest),
    " or ", script_reference, " from the repo root."
  )
}

# Read the current paper's LaTeX cross-reference data.  Writing excerpts use
# these labels for omitted references and retained counters; coding samples use
# the same labels when reproducing paper-formatted tables.

tex_crossref_ids <- function(path) {
  if (!file.exists(path)) return(character())
  text <- paste(readLines(path, warn = FALSE), collapse = "\n")
  hits <- regmatches(
    text,
    gregexpr("\\\\label\\{(?:tbl|fig|eq)-[A-Za-z0-9_-]+\\}", text, perl = TRUE)
  )[[1L]]
  if (!length(hits) || identical(hits, "")) return(character())
  sub("\\}$", "", sub("^\\\\label\\{", "", hits, perl = TRUE), perl = TRUE)
}

paper_reference_aux_path <- function(source) {
  file.path(
    dirname(source),
    paste0(tools::file_path_sans_ext(basename(source)), "-reference-labels.aux")
  )
}

read_latex_reference_labels <- function(path) {
  if (!file.exists(path)) {
    stop("Full-paper reference index is missing: ", path, call. = FALSE)
  }
  lines <- readLines(path, warn = FALSE)
  pattern <- "^\\\\newlabel\\{([^}]+)\\}\\{\\{([^}]*)\\}"
  hits <- regexec(pattern, lines, perl = TRUE)
  parts <- regmatches(lines, hits)
  parts <- parts[lengths(parts) == 3L]
  if (!length(parts)) {
    stop("Full-paper reference index contains no LaTeX labels: ", path, call. = FALSE)
  }

  ids <- vapply(parts, `[[`, character(1), 2L)
  numbers <- vapply(parts, `[[`, character(1), 3L)
  keep <- nzchar(ids) & nzchar(numbers)
  ids <- ids[keep]
  numbers <- numbers[keep]

  grouped <- split(numbers, ids)
  conflicts <- names(grouped)[vapply(grouped, function(x) length(unique(x)) > 1L, logical(1))]
  if (length(conflicts)) {
    stop(
      "Full-paper reference index contains conflicting numbers for: ",
      paste(conflicts, collapse = ", "),
      call. = FALSE
    )
  }
  vapply(grouped, function(x) unique(x)[[1L]], character(1))
}

crossref_display_name <- function(id) {
  prefix <- sub("-.*$", "", id)
  switch(prefix,
    sec = "Section",
    tbl = "Table",
    fig = "Figure",
    eq = "Equation",
    stop("Unsupported Quarto cross-reference ID: ", id, call. = FALSE)
  )
}


# Serialize metadata for Quarto, which follows YAML 1.2 boolean syntax.
quarto_yaml_lines <- function(x, indent.mapping.sequence = FALSE) {
  text <- yaml::as.yaml(
    x,
    indent.mapping.sequence = indent.mapping.sequence,
    handlers = list(logical = yaml::verbatim_logical)
  )
  strsplit(text, "\n", fixed = TRUE)[[1]]
}

render_qmd_to_pdf <- function(input_qmd, output_file) {
  input_qmd <- normalizePath(input_qmd, mustWork = TRUE)
  output_dir <- dirname(output_file)
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  output_dir <- normalizePath(output_dir, mustWork = TRUE)
  output_file <- file.path(output_dir, basename(output_file))
  rendered_name <- basename(output_file)

  quarto <- Sys.which("quarto")
  if (!nzchar(quarto)) stop("Quarto CLI was not found on PATH; cannot render ", input_qmd, call. = FALSE)

  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)
  setwd(dirname(input_qmd))

  status <- system2(quarto, c("render", basename(input_qmd), "--to", "pdf", "--output", rendered_name))
  if (!identical(status, 0L)) stop("quarto render failed for ", input_qmd, call. = FALSE)

  rendered_path <- file.path(dirname(input_qmd), rendered_name)
  if (!file.exists(rendered_path)) stop("Expected rendered PDF was not created: ", rendered_path, call. = FALSE)
  if (!identical(normalizePath(rendered_path, mustWork = TRUE), output_file)) {
    ok <- file.copy(rendered_path, output_file, overwrite = TRUE)
    if (!isTRUE(ok)) stop("Could not copy rendered PDF to ", output_file, call. = FALSE)
  }
  if (!file.exists(output_file)) stop("Rendered PDF was not available at expected output path: ", output_file, call. = FALSE)
  invisible(output_file)
}

pdf_page_count <- function(path) {
  pdfinfo <- Sys.which("pdfinfo")
  if (!nzchar(pdfinfo)) stop("pdfinfo is required to validate application-sample page counts.", call. = FALSE)
  info <- system2(pdfinfo, shQuote(path), stdout = TRUE, stderr = TRUE)
  status <- attr(info, "status") %||% 0L
  if (!identical(status, 0L)) stop("pdfinfo failed for ", path, call. = FALSE)
  page_line <- grep("^Pages:[[:space:]]+[0-9]+", info, value = TRUE)
  if (length(page_line) != 1L) stop("Could not read PDF page count for ", path, call. = FALSE)
  as.integer(sub("^Pages:[[:space:]]+", "", page_line))
}

check_writing_sample_page_counts <- function(paths, expected_pages) {
  if (length(paths) != length(expected_pages)) {
    stop("Writing-sample paths and page targets must have the same length.", call. = FALSE)
  }
  expected_pages <- as.integer(expected_pages)
  checked <- which(!is.na(expected_pages))
  if (!length(checked)) return(invisible(TRUE))

  actual_pages <- vapply(paths[checked], pdf_page_count, integer(1))
  mismatch <- actual_pages != expected_pages[checked]
  if (any(mismatch)) {
    details <- paste0(
      basename(paths[checked][mismatch]), ": ", actual_pages[mismatch],
      " pages (target ", expected_pages[checked][mismatch], ")"
    )
    # Final builds reject target warning conditions. Page targets are temporarily
    # advisory while sample formatting is still changing, so report the mismatch
    # prominently in the build log without recording a target warning.
    message(
      "WARNING: Writing-sample page counts differ from their current targets:\n- ",
      paste(details, collapse = "\n- "),
      "\nUpdate application-samples/samples.yml after sample formatting is settled."
    )
  }
  invisible(TRUE)
}

validate_anonymous_sample <- function(path, forbidden_strings) {
  forbidden_strings <- unique(as.character(unlist(forbidden_strings, use.names = FALSE)))
  forbidden_strings <- forbidden_strings[nzchar(forbidden_strings)]
  if (!length(forbidden_strings)) return(invisible(TRUE))
  pdftotext <- Sys.which("pdftotext")
  if (!nzchar(pdftotext)) stop("pdftotext is required to validate anonymous application samples.", call. = FALSE)
  text <- system2(pdftotext, c(shQuote(path), "-"), stdout = TRUE, stderr = TRUE)
  status <- attr(text, "status") %||% 0L
  if (!identical(status, 0L)) stop("pdftotext failed for ", path, call. = FALSE)
  collapsed <- paste(text, collapse = "\n")
  hits <- forbidden_strings[vapply(forbidden_strings, grepl, logical(1), x = collapsed, fixed = TRUE)]
  if (length(hits)) {
    stop("Anonymous sample contains identifying text: ", paste(hits, collapse = ", "), call. = FALSE)
  }
  invisible(TRUE)
}
