# Shared rendering and validation helpers for application-sample PDFs.


# Application samples use the current paper's PDF typography and page geometry.
# The paper gets its standard article class from the project configuration; sample
# QMDs are rendered from a nested work directory, so set that class explicitly.
paper_sample_metadata <- function(source_metadata, variant, manifest) {
  meta <- source_metadata
  meta$thanks <- NULL
  meta$author <- manifest$identity[[variant]]$author
  meta$format <- meta$format %||% list()
  meta$format$pdf <- utils::modifyList(
    meta$format$pdf %||% list(),
    list(documentclass = "article", `pdf-engine` = "xelatex")
  )
  meta
}


paper_title_with_subtitle <- function(source_metadata) {
  parts <- trimws(as.character(c(source_metadata$title %||% "", source_metadata$subtitle %||% "")))
  parts <- parts[nzchar(parts)]
  if (!length(parts)) stop("Current paper metadata must include a title.", call. = FALSE)
  paste(parts, collapse = ": ")
}

quoted_paper_title <- function(source_metadata) {
  paste0("“", paper_title_with_subtitle(source_metadata), "”")
}

application_sample_build_script <- function() {
  "scripts/run_full_build.sh"
}

application_sample_build_script_url <- function(manifest) {
  repository_url <- sub("/+$", "", manifest$paper$repository_url %||% "")
  if (!nzchar(repository_url)) stop("Application-sample manifest is missing paper.repository_url.", call. = FALSE)
  paste0(repository_url, "/blob/main/", application_sample_build_script())
}

application_sample_availability_sentence <- function(variant, manifest) {
  if (!identical(variant, "named")) return(character())
  paste0(
    "The full [paper](", manifest$paper$full_paper_url, ") and [repository](",
    manifest$paper$repository_url, ") are available online."
  )
}

application_sample_build_sentence <- function(variant, manifest) {
  script <- application_sample_build_script()
  script_reference <- if (identical(variant, "named")) {
    paste0("[`", script, "`](", application_sample_build_script_url(manifest), ")")
  } else {
    paste0("`", script, "`")
  }
  paste0(
    "This PDF can be generated by running `make samples` or ", script_reference,
    " from the repo root."
  )
}

# Serialize metadata for Quarto, which follows YAML 1.2 boolean syntax.
quarto_yaml_lines <- function(x, indent.mapping.sequence = FALSE) {
  text <- yaml::as.yaml(
    x,
    indent.mapping.sequence = indent.mapping.sequence,
    handlers = list(logical = yaml::verbatim_logical)
  )
  strsplit(text, "\n", fixed = TRUE)[[1]]
}

render_qmd_to_pdf <- function(input_qmd, output_file) {
  input_qmd <- normalizePath(input_qmd, mustWork = TRUE)
  output_dir <- dirname(output_file)
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  output_dir <- normalizePath(output_dir, mustWork = TRUE)
  output_file <- file.path(output_dir, basename(output_file))
  rendered_name <- basename(output_file)

  quarto <- Sys.which("quarto")
  if (!nzchar(quarto)) stop("Quarto CLI was not found on PATH; cannot render ", input_qmd, call. = FALSE)

  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)
  setwd(dirname(input_qmd))

  status <- system2(quarto, c("render", basename(input_qmd), "--to", "pdf", "--output", rendered_name))
  if (!identical(status, 0L)) stop("quarto render failed for ", input_qmd, call. = FALSE)

  rendered_path <- file.path(dirname(input_qmd), rendered_name)
  if (!file.exists(rendered_path)) stop("Expected rendered PDF was not created: ", rendered_path, call. = FALSE)
  if (!identical(normalizePath(rendered_path, mustWork = TRUE), output_file)) {
    ok <- file.copy(rendered_path, output_file, overwrite = TRUE)
    if (!isTRUE(ok)) stop("Could not copy rendered PDF to ", output_file, call. = FALSE)
  }
  if (!file.exists(output_file)) stop("Rendered PDF was not available at expected output path: ", output_file, call. = FALSE)
  invisible(output_file)
}

pdf_page_count <- function(path) {
  pdfinfo <- Sys.which("pdfinfo")
  if (!nzchar(pdfinfo)) stop("pdfinfo is required to validate application-sample page counts.", call. = FALSE)
  info <- system2(pdfinfo, shQuote(path), stdout = TRUE, stderr = TRUE)
  status <- attr(info, "status") %||% 0L
  if (!identical(status, 0L)) stop("pdfinfo failed for ", path, call. = FALSE)
  page_line <- grep("^Pages:[[:space:]]+[0-9]+", info, value = TRUE)
  if (length(page_line) != 1L) stop("Could not read PDF page count for ", path, call. = FALSE)
  as.integer(sub("^Pages:[[:space:]]+", "", page_line))
}

check_writing_sample_page_counts <- function(paths, expected_pages) {
  if (length(paths) != length(expected_pages)) {
    stop("Writing-sample paths and page targets must have the same length.", call. = FALSE)
  }
  expected_pages <- as.integer(expected_pages)
  checked <- which(!is.na(expected_pages))
  if (!length(checked)) return(invisible(TRUE))

  actual_pages <- vapply(paths[checked], pdf_page_count, integer(1))
  mismatch <- actual_pages != expected_pages[checked]
  if (any(mismatch)) {
    details <- paste0(
      basename(paths[checked][mismatch]), ": ", actual_pages[mismatch],
      " pages (target ", expected_pages[checked][mismatch], ")"
    )
    # Final builds reject target warning conditions. Page targets are temporarily
    # advisory while sample formatting is still changing, so report the mismatch
    # prominently in the build log without recording a target warning.
    message(
      "WARNING: Writing-sample page counts differ from their current targets:\n- ",
      paste(details, collapse = "\n- "),
      "\nUpdate application-samples/samples.yml after sample formatting is settled."
    )
  }
  invisible(TRUE)
}

validate_anonymous_sample <- function(path, forbidden_strings) {
  forbidden_strings <- unique(as.character(unlist(forbidden_strings, use.names = FALSE)))
  forbidden_strings <- forbidden_strings[nzchar(forbidden_strings)]
  if (!length(forbidden_strings)) return(invisible(TRUE))
  pdftotext <- Sys.which("pdftotext")
  if (!nzchar(pdftotext)) stop("pdftotext is required to validate anonymous application samples.", call. = FALSE)
  text <- system2(pdftotext, c(shQuote(path), "-"), stdout = TRUE, stderr = TRUE)
  status <- attr(text, "status") %||% 0L
  if (!identical(status, 0L)) stop("pdftotext failed for ", path, call. = FALSE)
  collapsed <- paste(text, collapse = "\n")
  hits <- forbidden_strings[vapply(forbidden_strings, grepl, logical(1), x = collapsed, fixed = TRUE)]
  if (length(hits)) {
    stop("Anonymous sample contains identifying text: ", paste(hits, collapse = ", "), call. = FALSE)
  }
  invisible(TRUE)
}
