#!/usr/bin/env bash
set -euo pipefail

out="${1:-Archive.zip}"
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

required_public_outputs=(
  "paper/report.pdf"
  "paper/report.html"
  "docs/district-matching.html"
  "docs/long-paths-and-8-3-filenames.html"
  "application-samples/output/RishavRoy_WritingSample.pdf"
  "application-samples/output/RishavRoy_WritingSample10pg.pdf"
  "application-samples/output/RishavRoy_WritingSample5pg.pdf"
  "application-samples/output/RishavRoy_CodingSample.pdf"
  "application-samples/output/RishavRoy_CodingSample47pg.pdf"
  "application-samples/output/RishavRoy_CodingSample25pg.pdf"
)


if [[ ! -f .public-final-ok ]]; then
  printf 'Cannot build review archive because .public-final-ok is missing. Run make check-public-final successfully first.\n' >&2
  exit 1
fi

missing=()
for f in "${required_public_outputs[@]}"; do
  if [[ ! -s "$f" ]]; then
    missing+=("$f")
  fi
done
if (( ${#missing[@]} )); then
  printf 'Cannot build review archive because required public outputs are missing or empty:\n' >&2
  printf '  - %s\n' "${missing[@]}" >&2
  printf 'Run make clean-renders && make check-public-final before packaging.\n' >&2
  exit 1
fi

# Copy the working tree, not git archive HEAD, so the archive matches the files
# just regenerated by the local run. This intentionally excludes local-only
# stores/caches/raw data below.
python3 - "$tmpdir" <<'PY'
import os, shutil, sys
from pathlib import Path

dst = Path(sys.argv[1]).resolve()
src = Path.cwd().resolve()

skip_dirs = {
    '.git', '_targets', '.quarto-home', '.texcache', '.quarto', '.Rproj.user',
    '__MACOSX', 'relevant-literature',
}
skip_parts = {
    ('renv', 'library'), ('renv', 'staging'), ('renv', 'cache'),
    ('application-samples', '.work'), ('scripts', '__pycache__'),
    ('data', 'raw'), ('data', 'raw_future'),
    ('archive', 'implementation-bundles'),
}
skip_files = {'Archive.zip', 'legacy.zip', 'data.zip', 'full_output.txt', 'file_list.txt', '.public-final-ok'}
skip_suffixes = {'.aux', '.log', '.fls', '.fdb_latexmk', '.toc', '.out', '.bbl', '.blg'}
skip_exact_names = {'.DS_Store', '.RData', '.Rhistory', '.RDataTmp'}

for root, dirs, files in os.walk(src):
    rel_root = Path(root).resolve().relative_to(src)
    parts = rel_root.parts
    dirs[:] = [d for d in dirs if d not in skip_dirs and (parts + (d,)) not in skip_parts and not d.endswith('_cache') and not d.endswith('_files') and d != '__pycache__']
    for name in files:
        if name in skip_files or name in skip_exact_names or name.endswith('.nb.html') or name.endswith('.synctex.gz') or Path(name).suffix in skip_suffixes:
            continue
        rel = rel_root / name
        if rel.parts[:2] in skip_parts:
            continue
        out = dst / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src / rel, out)
PY

# Heavy planning/archive files are tracked but omitted from review bundles.
rm -f "$tmpdir/docs/plan/THOROUGH NOTES Research Paper ECON 623.docx" \
      "$tmpdir/docs/plan/COMPACTED NOTES Research Paper ECON 623.docx"
rm -rf "$tmpdir/archive/implementation-bundles"
find "$tmpdir" -name '.DS_Store' -delete

rm -f "$out"
(cd "$tmpdir" && zip -r "$OLDPWD/$out" . >/dev/null)

if unzip -l "$out" | grep -E '(^|/)(_targets|renv/library|application-samples/\.work|scripts/__pycache__|\.quarto-home|\.texcache|__MACOSX|\.DS_Store)(/|$)' >/dev/null; then
  echo "Review archive contains local-only cache artifacts." >&2
  exit 1
fi

echo "Wrote $out"
