---
title: "Coding Sample: Escaping Inequality in India"
author: "Rishav Roy"
format:
  pdf:
    documentclass: article
    papersize: letter
    geometry:
      - left=.9in
      - right=.9in
      - top=1in
      - bottom=1in
      - footskip=30pt
execute:
  echo: false
---

What follows is the 138-page code appendix to my independent paper and writing sample, "Escaping Inequality in India: The Role of English-Medium Instruction."

Due to the length of this code, the time-constrained reviewer is encouraged to prioritize these 47 pages, excerpted from the code chunks listed below them:

14-16. Scalable **import, cleaning, and merging** of multi-file census and geospatial data.

   - Chunk 4: Import key data files

31-32. **QA checks, disambiguation of identifiers** for district-level crosswalk.

   - Chunk 6: Match districts: Construct district tracking dfs

50-52. **Testing for systematic missingness** using the Benjamini–Hochberg procedure and parallelized logistic regressions.

   - Chunk 8: Participation model: Are NAs randomly distributed

55-57. **Survey-weighted probit estimation**, average marginal effects derivation, and setup for sample selection correction under a complex survey design.

   - Chunk 9: Participation model: Estimation and IMR
   - Chunk 10: Participation model: Derive AME

80-88. Reusable **record-linkage functions** using cascading fuzzy matches and unmatched/false-match diagnostics to harmonize district identifiers across years and data sources.

   - Chunk 16: Match districts: Test joining methods
   - Chunk 17: Match districts: Define joining functions

105-107. Reusable **IV specification and estimation pipeline** with clustered inference, plus contiguity-based spatial weights and setup for spatially lagged models.

   - Chunk 24: Geospatial: Neighbor list construction
   - Chunk 25: 2SLS: Controls and 2SLS formula
   - Chunk 26: 2SLS: Baseline 2SLS models

111-112. **Robustness checks and diagnostics** for multicollinearity, spatial autocorrelation.

   - Chunk 28: Multicollinearity check
   - Chunk 29: Geospatial: Spatial autocorrelation tests

117-138. **Automated generation of publication-quality figures and tables** (including both summary statistics and regression outputs).

   - Chunks 31-40: [Output for paper]
